### ISSUE TITLE
Atualizar Readme

### ISSUE THREAD

**Issue by GoliasVictor** [GoliasVictor/LivrEtec#38]

**Comment by GoliasVictor** [comment]
Tem que atualizar o read me adicionando ainda os comandos para executar o docker e falar das outras tecnologias envolvvidas, que são gRPC e MAUI

**Comment by lucascesar918** [comment]
acho que é uma melhor ideia você fazer essa parte do readme e eu corrigir depois, já que foi você que implementou 100%

**Comment by GoliasVictor** [comment]
Então, por enquanto acho que o readme já tá atualizado o suficiente,  ai só queria que tu desse uma revisão básica da ortografia já que sou meio analfabeto
